name: Static Analysis

on: ['push', 'pull_request']

jobs:
  pint:
    runs-on: ubuntu-latest

    name: Pint

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: zip
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --prefer-dist --no-progress --ansi

    - name: Run Pint
      run: vendor/bin/pint --test --ansi

  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --prefer-dist --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi
